#!/bin/sh

# Don't give an error if, for example, postfix is not installed.
mkdir /var/spool/postfix/etc/ssl || true
mkdir /var/spool/postfix/etc/ssl/certs || true
cp /etc/ssl/certs/ca-certificates.crt /var/spool/postfix/etc/ssl/certs/ca-certificates.crt || true
