#!/bin/sh

if [ ! -d /var/spool/postfix ]; then
    echo "Postfix chroot not found, skipping copying CA certs"
    exit 0
fi

mkdir -p /var/spool/postfix/etc/ssl
cp -r /etc/ssl/certs /var/spool/postfix/etc/ssl/
